.Dd
.Dt README 7
.Os 3cl
.
.Sh NAME
.Nm 3cl
.Nd c cool char lang interpreter
.
.Sh DESCRIPTION
.Nm
is an interpreter
of cool char lang
which is a brainfuck-like langauge,
but different
and with more features.
.
.Sh SEE ALSO
.Xr 3cl 1 ,
.Xr ccl 7 ,
.Lk https://github.com/holy-8/cool_char_lang Original implementation
